#!/bin/bash

# Script to update .env.local with actual keys from local Supabase instance
# Usage: ./update-local-env.sh

echo "🔍 Checking local Supabase status..."

# Check if Supabase is running
if ! supabase status &> /dev/null; then
    echo "❌ Local Supabase is not running!"
    echo "   Please run: supabase start"
    exit 1
fi

echo "✅ Local Supabase is running"
echo ""
echo "📋 Getting credentials from Supabase..."

# Get the publishable key from supabase status
PUBLISHABLE_KEY=$(supabase status | grep "Publishable key:" | awk '{print $3}')

if [ -z "$PUBLISHABLE_KEY" ]; then
    echo "❌ Could not get publishable key from Supabase"
    echo "   Please run: supabase status"
    exit 1
fi

echo "✅ Found publishable key: $PUBLISHABLE_KEY"
echo ""

# Create or update .env.local
cat > .env.local << EOF
# ============================================
# LOCAL DEVELOPMENT ENVIRONMENT VARIABLES
# ============================================
# This file is for local Supabase development.
# It overrides .env settings when running locally.
# 
# Auto-generated by update-local-env.sh
# Last updated: $(date)
# ============================================

# Local Supabase Configuration
# These keys are from your running local Supabase instance

# Next.js environment variables (primary)
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_ANON_KEY=$PUBLISHABLE_KEY
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=$PUBLISHABLE_KEY
NEXT_PUBLIC_SUPABASE_PROJECT_ID=local

# Vite environment variables (for backwards compatibility)
VITE_SUPABASE_URL=http://127.0.0.1:54321
VITE_SUPABASE_PUBLISHABLE_KEY=$PUBLISHABLE_KEY
VITE_SUPABASE_ANON_KEY=$PUBLISHABLE_KEY
VITE_SUPABASE_PROJECT_ID=local

# ============================================
# LOCAL SUPABASE SERVICES
# ============================================
# API URL: http://127.0.0.1:54321
# Studio (DB UI): http://127.0.0.1:54323
# Mailpit (Email Testing): http://127.0.0.1:54324
# Database: postgresql://postgres:postgres@127.0.0.1:54322/postgres
# ============================================

# Payment Gateway Configuration (Test Mode)
# Use test keys for local development
RZP_TEST_KEY_ID=your-razorpay-test-key-id
RZP_TEST_KEY_SECRET=your-razorpay-test-key-secret
RZP_WEBHOOK_SECRET=your-webhook-secret

# Email Service Configuration (Optional for local dev)
# Leave empty to skip email sending in local development
# Or use Resend test key if you want to test emails
RESEND_API_KEY=

# ============================================
# NOTES
# ============================================
# - The keys above are from your local Supabase instance
# - These keys are safe to commit as they only work with local Supabase
# - To get the service role key, run: supabase status
# - To switch back to remote, rename this file or delete it
# - Local Supabase includes seed data automatically
# - To regenerate this file, run: ./update-local-env.sh
# ============================================
EOF

echo "✅ .env.local has been updated!"
echo ""
echo "📝 Summary:"
echo "   - URL: http://127.0.0.1:54321"
echo "   - Key: $PUBLISHABLE_KEY"
echo ""
echo "🚀 Next steps:"
echo "   1. Restart your dev server: npm run dev"
echo "   2. The app will now use local Supabase"
echo ""
echo "💡 To view all Supabase services:"
echo "   - Studio: http://127.0.0.1:54323"
echo "   - Mailpit: http://127.0.0.1:54324"

