-- Add short_code column to events and slug column to communities
-- These columns support short URLs (/e/:shortCode) and community slugs (/c/:slug)
-- Both columns already exist in production with backfilled data.

-- ============================================================================
-- EVENTS: short_code column
-- ============================================================================

ALTER TABLE public.events
ADD COLUMN IF NOT EXISTS short_code TEXT;

-- Unique index (partial - only non-null values)
CREATE UNIQUE INDEX IF NOT EXISTS idx_events_short_code
ON public.events (short_code)
WHERE short_code IS NOT NULL;

COMMENT ON COLUMN public.events.short_code IS 'Unique 8-char alphanumeric code for short event URLs (/e/:shortCode). Generated by admin panel on creation.';

-- ============================================================================
-- COMMUNITIES: slug column
-- ============================================================================

ALTER TABLE public.communities
ADD COLUMN IF NOT EXISTS slug TEXT;

-- Unique index (partial - only non-null values)
CREATE UNIQUE INDEX IF NOT EXISTS idx_communities_slug
ON public.communities (slug)
WHERE slug IS NOT NULL;

COMMENT ON COLUMN public.communities.slug IS 'URL-friendly slug derived from community name for short URLs (/c/:slug). Generated by admin panel on creation.';

