// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

<<<<<<< HEAD
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error('Missing Supabase environment variables. Please check your .env file.');
}
=======
const SUPABASE_URL = "https://ggochdssgkfnvcrrmtlp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdnb2NoZHNzZ2tmbnZjcnJtdGxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTIxMTksImV4cCI6MjA2OTk2ODExOX0.LySB5o7Gpe-jReI7wylEPQE0obQTTYba4q_koQhnDx0";
>>>>>>> 193db8a94be7a7b5ace78e2adf90eaea66f0146c

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});